name = "masterselects"
compatibility_date = "2026-03-18"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "masterselects"
database_id = "a2f0a1aa-6bd9-4c75-9406-d09b93635eac"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "daadda485425465791a1c83afc48be67"

[vars]
ENVIRONMENT = "development"
